/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views_pkg;

import controller_pkg.Conection;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SUPERFERRETERIA
 */
public class Departmens extends javax.swing.JFrame {
    Conection con = new Conection();
    Connection cn;
    Statement st;
    ResultSet rs;
    DefaultTableModel modelo;
    void show_departments(){
        String sql = "SELECT * FROM tb_department";
        try{
            cn = con.getConnection();
            st = cn.createStatement();
            rs = st.executeQuery(sql);
            //Los datos que devuelve la consulta se muestran en la tabla
            Object[]department = new Object[3];
            modelo = (DefaultTableModel)tb_departments.getModel();
            while(rs.next()){
                department[0] = rs.getInt("id");
                department[1] = rs.getString("department");
                department[2] = rs.getInt("cant_employee");
                modelo.addRow(department);
                System.out.println(rs.getInt("id"));
            }
            tb_departments.setModel(modelo);
        }catch(SQLException e){
            
        }
    }
    
    void clear_rows_table(){
        for (int i = 0; i < tb_departments.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i-1;
        }
        
    }
    
    void edit_department(){
        //Hacemos nuevamente lectura de los valores contenidos en los JTextField
        //Para identificar si el usuario modifico algún valor
        Add_Edit_Depart edit_depart = new Add_Edit_Depart(this, true);
        edit_depart.action_performer=2;
        edit_depart.setLocationRelativeTo(null);
        int fila = tb_departments.getSelectedRow();
        if (fila >= 0) {
        Object[] filaselect = {
                tb_departments.getValueAt(fila, 0),
                tb_departments.getValueAt(fila, 1),
                tb_departments.getValueAt(fila, 2)};
        edit_depart.setTxt_code(String.valueOf(filaselect[0]));
        edit_depart.setTxt_department(String.valueOf(filaselect[1]));
        edit_depart.setTxt_employees(String.valueOf(filaselect[2]));
        }
        edit_depart.setVisible(true);
        clear_rows_table();
        show_departments();
        
    }
    
    
    void delete_department(){
        int fila = tb_departments.getSelectedRow();
        int id  = Integer.parseInt((String)tb_departments.getValueAt(fila, 0).toString());
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "No has seleccionado un departamento");
        }else{
            
            System.out.println("ID: " + id);
            String query = "DELETE FROM tb_department WHERE id = " + id;
            try{
                cn = con.getConnection();
                st = cn.createStatement();
                st.executeUpdate(query);
                JOptionPane.showMessageDialog(this, "El departmento ha sido eliminado con exito");
                clear_rows_table();
                show_departments();
            }catch(HeadlessException | SQLException e){
            }
        }
    }


    void add_department(){
        Add_Edit_Depart add_depart = new Add_Edit_Depart(this, true);
        add_depart.action_performer=1;
        add_depart.setLocationRelativeTo(null);
        add_depart.setVisible(true);
        clear_rows_table();
        show_departments();
        
           
    }




    /**
     * Creates new form Departmens
     */
    public Departmens() {
        initComponents();
        setLocationRelativeTo(null);
        show_departments();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_departments = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        btn_edit_department = new javax.swing.JButton();
        btn_add_department = new javax.swing.JButton();
        btn_delete_department = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        tb_departments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Departamento", "Numero empleados"
            }
        ));
        tb_departments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_departmentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_departments);

        jLabel5.setText("DEPARTAMENTOS MINTIC");

        btn_edit_department.setText("Editar Departamento");
        btn_edit_department.setEnabled(false);
        btn_edit_department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_departmentActionPerformed(evt);
            }
        });

        btn_add_department.setText("Añadir Departamento");
        btn_add_department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_departmentActionPerformed(evt);
            }
        });

        btn_delete_department.setText("Eliminar Departamento");
        btn_delete_department.setEnabled(false);
        btn_delete_department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_departmentActionPerformed(evt);
            }
        });

        jButton1.setText("Consultar Empleados");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btn_add_department)
                .addGap(97, 97, 97)
                .addComponent(btn_edit_department)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(btn_delete_department)
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(300, 300, 300))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add_department)
                    .addComponent(btn_edit_department)
                    .addComponent(btn_delete_department))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButton1)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_departmentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_departmentsMouseClicked
        // TODO add your handling code here:
         // TODO add your handling code here:
        int row = tb_departments.getSelectedRow();
        btn_delete_department.setEnabled(true);
        btn_edit_department.setEnabled(true);
        System.out.println(row);
        if(row < 0){
            JOptionPane.showMessageDialog(this, "Debes seleccionar un departamento");
        }else{
            int id  = Integer.parseInt((String)tb_departments.getValueAt(row, 0).toString());
            int employees  = Integer.parseInt((String)tb_departments.getValueAt(row, 2).toString());
            String department = (String)tb_departments.getValueAt(row, 1);
            System.out.println(id + " - " + employees + " - " + department);
          
        }
    }//GEN-LAST:event_tb_departmentsMouseClicked

    private void btn_edit_departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_departmentActionPerformed
        // TODO add your handling code here:
        edit_department(); 
        
        
    }//GEN-LAST:event_btn_edit_departmentActionPerformed

    private void btn_add_departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_departmentActionPerformed
        // TODO add your handling code here:
        add_department();
       
        
        
    }//GEN-LAST:event_btn_add_departmentActionPerformed

    private void btn_delete_departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_departmentActionPerformed
        // TODO add your handling code here:
        delete_department();
    }//GEN-LAST:event_btn_delete_departmentActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Employees int_emplo = new Employees(this, true);
        int_emplo.setLocationRelativeTo(null);
        int_emplo.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Departmens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Departmens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Departmens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Departmens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Departmens().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_department;
    private javax.swing.JButton btn_delete_department;
    private javax.swing.JButton btn_edit_department;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_departments;
    // End of variables declaration//GEN-END:variables
}
