/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views_pkg;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import controller_pkg.Conection;
import java.awt.HeadlessException;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author SUPERFERRETERIA
 */
public class Employees extends javax.swing.JFrame {

    /**
     * Creates new form Employees
     */
    Conection con = new Conection();
    Connection cn;
    Statement st;
    ResultSet rs;
    DefaultTableModel modelo;

   void show_employees(){
        String sql = "SELECT * FROM tb_employee";
        try{
            cn = con.getConnection();
            st = cn.createStatement();
            rs = st.executeQuery(sql);
            //Los datos que devuelve la consulta se muestran en la tabla
            Object[]employee = new Object[4];
            modelo = (DefaultTableModel)tb_employees.getModel();
            while(rs.next()){
                employee[0] = rs.getInt("id");
                employee[1] = rs.getString("name");
                employee[2] = rs.getInt("document");
                employee[3] = rs.getInt("id_department");
                modelo.addRow(employee);
                System.out.println(employee[0]);
            }
            tb_employees.setModel(modelo);
        }catch(SQLException e){
            
        }
    }
   void clear_rows_table(){
        for (int i = 0; i < tb_employees.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i-1;
        }
        
    }
   
   void add_employees(){
        Add_Edit_employee add_emplo = new Add_Edit_employee(this, true);
        add_emplo.action_performer=1;
        add_emplo.setLocationRelativeTo(null);
        add_emplo.setVisible(true);
        clear_rows_table();
        show_employees();
        
           
    }
    void edit_employees(){
        //Hacemos nuevamente lectura de los valores contenidos en los JTextField
        //Para identificar si el usuario modifico algún valor
        Add_Edit_employee edit_employee = new Add_Edit_employee(this, true);
        edit_employee.action_performer=2;
        edit_employee.setLocationRelativeTo(null);
        int fila = tb_employees.getSelectedRow();
        if (fila >= 0) {
        Object[] filaselect = {
                tb_employees.getValueAt(fila, 0),
                tb_employees.getValueAt(fila, 1),
                tb_employees.getValueAt(fila, 2),
        tb_employees.getValueAt(fila, 3)};
        edit_employee.setTxt_id(String.valueOf(filaselect[0]));
        edit_employee.setTxt_employee(String.valueOf(filaselect[1]));
        edit_employee.setTxt_document(String.valueOf(filaselect[2]));
        edit_employee.setTxt_department(String.valueOf(filaselect[3]));
        }
        edit_employee.setVisible(true);
        clear_rows_table();
        show_employees();
    }
    
    void delete_employees(){
        int fila = tb_employees.getSelectedRow();
        int id  = Integer.parseInt((String)tb_employees.getValueAt(fila, 0).toString());
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "No has seleccionado un departamento");
        }else{
            
            System.out.println("ID: " + id);
            String query = "DELETE FROM tb_employee WHERE id = " + id;
            try{
                cn = con.getConnection();
                st = cn.createStatement();
                st.executeUpdate(query);
                JOptionPane.showMessageDialog(this, "El empleado ha sido eliminado con exito");
                clear_rows_table();
                show_employees();
            }catch(HeadlessException | SQLException e){
            }
        }
    }

    public Employees(java.awt.Frame parent, boolean modal) {
        initComponents();
        setLocationRelativeTo(null);
        show_employees();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_add_employees = new javax.swing.JButton();
        btn_edit_employees = new javax.swing.JButton();
        btn_delete_employees = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_employees = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("EMPLEADOS MINTIC");

        btn_add_employees.setText("Añadir empleados");
        btn_add_employees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_employeesActionPerformed(evt);
            }
        });

        btn_edit_employees.setText("Editar Empleados");
        btn_edit_employees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_employeesActionPerformed(evt);
            }
        });

        btn_delete_employees.setText("Eliminar Empleados");
        btn_delete_employees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_employeesActionPerformed(evt);
            }
        });

        tb_employees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Departamento", "Nombre", "N° Documento", "Departamento"
            }
        ));
        jScrollPane1.setViewportView(tb_employees);

        jButton4.setText("Regresar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_add_employees)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_edit_employees)
                        .addGap(64, 64, 64)
                        .addComponent(btn_delete_employees)
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 28, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_edit_employees)
                    .addComponent(btn_add_employees)
                    .addComponent(btn_delete_employees))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_add_employeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_employeesActionPerformed
        // TODO add your handling code here:
        add_employees();
    }//GEN-LAST:event_btn_add_employeesActionPerformed

    private void btn_edit_employeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_employeesActionPerformed
        // TODO add your handling code here:
        edit_employees();
    }//GEN-LAST:event_btn_edit_employeesActionPerformed

    private void btn_delete_employeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_employeesActionPerformed
        // TODO add your handling code here:
        delete_employees();
    }//GEN-LAST:event_btn_delete_employeesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Employees dialog = new Employees(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_employees;
    private javax.swing.JButton btn_delete_employees;
    private javax.swing.JButton btn_edit_employees;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_employees;
    // End of variables declaration//GEN-END:variables
}
